### ISSUE TITLE
compiler plugin doesn't work due to dated Hackage package

### ISSUE THREAD

**Issue by gshen42** [ucsd-progsys/liquidhaskell#1689]
I followed the [tutorial](https://github.com/ucsd-progsys/liquidhaskell/blob/develop/src/Language/Haskell/Liquid/GHC/Plugin/Tutorial.hs) for compiler plugin, but failed to compile package `liquidhaskell` with the following error message:

```
src/Language/Haskell/Liquid/GHC/Misc.hs:59:82: error:
    Module ‘Type’ does not export ‘isClassPred’
   |
59 | import           Type                                       (expandTypeSynonyms, isClassPred, isEqPred, liftedTypeKind)
   |                                                                                  ^^^^^^^^^^^

src/Language/Haskell/Liquid/GHC/Misc.hs:59:95: error:
    Module ‘Type’ does not export ‘isEqPred’
   |
59 | import           Type                                       (expandTypeSynonyms, isClassPred, isEqPred, liftedTypeKind)
   |                    
```

The problem is caused by the fact that the latest `liquidhaskell` on Hackage is compiled against `ghc-8.8`, whereas the compiler plugin requires `ghc-8.10.1` (which I'm using), and there's a breaking API change in `ghc-8.10.1` (function `isClassPred` and `isEqPred` are moved from module `Type` to `Predicate`), so the package from Hackage fails to compile.

Aside from update the package on Hackage, is there a workaround to try the compiler plugin, or am I missing anything?

**Comment by ranjitjhala** [comment]
Hi @gshen42, 

Unfortunately yes the only workaround is to use GHC 8.10 as the plugin 
requires features that were just added to that version of GHC.
 
The simplest way would be to follow these instructions:

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#step-2-install-liquid-from-source

LMK if that works!

- Ranjit.

**Comment by gshen42** [comment]
Thanks, @ranjitjhala. The standalone `liquid` executable works, but that's not the compiler plugin way I hope to use.

I somehow managed to get the latest `liquidhaskell` by listing the GitHub repo in the `extra-deps` field of my `stack.yaml`. It looks like this:

```
extra-deps:
...
- github: ucsd-progsys/liquid-fixpoint
  commit: 18ddfac7dafbe7472c1962a1e986677fbcd27515
- github: ucsd-progsys/liquidhaskell
  commit: 3bc467162ba285bf2c1529dafce21a20bb9aab8e
  subdirs:
  - liquid-ghc-prim
  - liquid-base
  - liquid-bytestring
  - liquid-prelude
  - liquid-vector
  - liquid-containers
  - liquid-parallel
  - liquid-platform
  - .
```

The `liquidhaskell` package builds successfully, however, when I try to type check this code:
```
{-@ one :: {v:Int | v > 0} @-}
one :: Int
one = 42
```
, I get this error:
```
/home/gshen/LH-playground/[src/Main.hs:6:12-27: Error: Illegal type specification for `Main.one`
     Main.one :: {v : GHC.Types.Int | v > 0}
     Sort Error in Refinement: {v : GHC.Types.Int | v > 0}
     The sort GHC.Types.Int is not numeric
  because
The sort GHC.Types.Int is not numeric]
```

Is there a way to fix this?
