### ISSUE TITLE
GADTs broken

### ISSUE THREAD

**Issue by sertel** [ucsd-progsys/liquidhaskell#1794]
Hi,

I use GADTs a lot in my project but it seems LH currently can't parse them.
Apart from my own code, I tried the test cases in `test/pos` at http://goto.ucsd.edu:8090/index.html and could not get any of them to parse.

I could not find an open issue on the topic. Is there a plan to fix this soon?

Thanks!

**Comment by ranjitjhala** [comment]
Can you paste a link to a specific file that’s not working for you? (The demo link is just to the default demo...)

**Comment by sertel** [comment]
For example, this one https://github.com/ucsd-progsys/liquidhaskell/blob/develop/tests/pos/ExactGADT2.hs

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1605306221_21735.hs

If I copy/paste this at http://goto.ucsd.edu:8090/index.html I get the very same parse errors that I get in my code. This accounts also for all the other `tests/pos/ExactGADT*` files in the repo.

**Comment by ranjitjhala** [comment]
The browser version is a bit old, I need to update it! 

The current LH "plugin" mode or built from source supports the above.

**Comment by sertel** [comment]
I just upgraded from version 0.8.10.1 (as pointed to here: https://github.com/ucsd-progsys/lh-plugin-demo/blob/main/stack.yaml and from the github website) to 0.8.10.2 (as promoted on Hackage) in my project. But I still see the above GADT use case failing with:
```
Cannot parse specification:
unexpected 'F'
expecting space, "->", "~>", "=>", white space, "|" or end of input
• 
 |
 |         FldY :: Field Int
 |         ^
```
I will try building Liquid Haskell from the github source tomorrow and report back.

**Comment by sertel** [comment]
The following setup finally worked for me:
```
resolver: nightly-2020-11-11
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 024dc7483d05a974fcf42ff3912c2672d74e27ce

  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 024dc7483d05a974fcf42ff3912c2672d74e27ce
    subdirs:
      - liquid-base

  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 024dc7483d05a974fcf42ff3912c2672d74e27ce
    subdirs:
      - liquid-ghc-prim

  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 90e19918bc51a2c246909ec1e4edba636077c675

  - th-compat-0.1@sha256:ff11df2bbd6ad519987f8fe5b2fd783349260681a91565a40d4096bb0a536b0b,2818
  - megaparsec-8.0.0@sha256:362f85e243ecbcb550e1de6e5c74ba5a50c09edaa1208c99bc5b9fd242227fc6,3808
```
