### ISSUE TITLE
Can't figure out how to build a project with GHC 9.6.3

### ISSUE THREAD

**Issue by lylek** [ucsd-progsys/liquidhaskell#2271]
Hi folks,

I'm new to LiquidHaskell. I was able to get the [LH Plugin Demo](https://github.com/ucsd-progsys/lh-plugin-demo) to build and run using `stack`. But I wanted to try making my own project, using GHC 9.6.3. The installation instructions said to add a dependency on `liquidhaskell` to your `.cabal` file, and to "follow the examples" for how to set up your `stack.yaml`.

Well, the LH Plugin Demo's `stack.yaml` references particular commits for `liquidhaskell` and `liquid-fixpoint`. So I looked up the `v0.9.6.3` tag, and copied the commit ID for `liquidhaskell`, and used the submodule commit ID for `liquid-fixpoint`. But when I build with `stack`, it terminated with this error:

```
liquidhaskell     > Error: setup: '/Users/lyle/.ghcup/ghc/9.6.3/bin/ghc' exited with an error:
liquidhaskell     > <command line>: Could not find module ‘LiquidHaskellBoot’
liquidhaskell     > Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

This is the `stack.yaml` I'm using for my project:

```
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/6.yaml

packages:
- .

extra-deps:
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 6aeb737d47d10734d74d193e176eef95dce65d57
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 28c6d943a18d8d636385a7ff1fa10e81a7b4a0ab
```

In `package.yaml`, I just made sure to set up `dependencies` like this:

```
dependencies:
- base >= 4.7 && < 5
- liquidhaskell
- liquid-prelude
```

I also added `-fplugin=LiquidHaskell` under `ghc-options`.

Since that failed, I tried to work from the other direction. What if I tried to upgrade the LH Plugin Demo to GHC 9.6.3? So I copied that project, and just edited the `stack.yaml`. I used the same `stackage` resolver that was set in the `stack.yaml` within the `liquidhaskell` project (at the `v0.9.6.3` tag):

```
resolver: nightly-2023-11-27
packages:
  - .
extra-deps:
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: fc4a89b91fad8b7a02b72901381d4358a470e230
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: eb339f9abdf073f8d9f0c446c309006fdf49ed42

nix:
  packages: [cacert, git, hostname, z3]
```

That failed to build, but with a different problem... `stack` couldn't construct a build plan:

```
Error: [S-4804]
       Stack failed to construct a build plan.

       While constructing the build plan, Stack encountered the following errors. The 'Stack configuration' refers to the set of package versions specified by the snapshot (after any dropped packages,
       or pruned GHC boot packages; if a boot package is replaced, Stack prunes all other such packages that depend on it) and any extra-deps:

       In the dependencies for liquid-fixpoint-0.9.0.2.1:
         * vector must match <0.13, but vector-0.13.1.0 is in the Stack configuration (latest matching version is 0.12.3.1).
       needed due to lh-plugin-demo-0.1.0.0 -> liquid-fixpoint-0.9.0.2.1

       In the dependencies for liquid-vector-0.12.3.1:
         * vector must match >=0.12.3.1 && <0.13, but vector-0.13.1.0 is in the Stack configuration (latest matching version is 0.12.3.1).
       needed due to lh-plugin-demo-0.1.0.0 -> liquid-vector-0.12.3.1

       In the dependencies for liquidhaskell-0.9.2.5.0:
         * bytestring must match ==0.11.3.1, but bytestring-0.11.5.2 is in the Stack configuration (latest matching version is 0.11.3.1).
         * containers must match ==0.6.5.1, but containers-0.6.7 is in the Stack configuration (latest matching version is 0.6.5.1).
       needed due to lh-plugin-demo-0.1.0.0 -> liquidhaskell-0.9.2.5.0

       In the dependencies for liquidhaskell-boot-0.9.2.5.0:
         * Cabal must match <3.7, but Cabal-3.10.1.0 is in the Stack configuration (latest matching version is 3.6.3.0).
         * ghc must match ^>=9.2, but ghc-9.6.3 is in the Stack configuration (latest matching version is 9.2.8).
         * hashable must match >=1.3 && <1.4, but hashable-1.4.3.0 is in the Stack configuration (latest matching version is 1.3.5.0).
         * optparse-applicative must match <0.18, but optparse-applicative-0.18.1.0 is in the Stack configuration (latest matching version is 0.17.1.0).
       needed due to lh-plugin-demo-0.1.0.0 -> liquidhaskell-boot-0.9.2.5.0
```

What am I missing? Is there an easier way to figure out how to configure my files? Could someone please add more instructions to the documentation?

Thanks,
Lyle
