### ISSUE TITLE
Generic measure specialization appears to remain unused

### ISSUE THREAD

**Issue by j6carey** [ucsd-progsys/liquidhaskell#649]
With a file `t.hs` containing:
```haskell
module T where

import Data.Proxy
import Data.Word

{-@ class measure sizeOf :: forall a . Proxy a -> Int @-}
{-@
instance measure sizeOf :: Proxy Word16 -> Int
sizeOf (Proxy) = 2
@-}
{-@
instance measure sizeOf :: Proxy Word32 -> Int
sizeOf (Proxy) = 4
@-}

{-@
bar :: { x : Int | x = (sizeOf (Proxy :: Proxy Word32)) }
    -> ()
@-}
bar :: Int -> ()
bar _ = ()

{-@
qux :: { x : Int | x = 4 }
    -> ()
@-}
qux :: Int -> ()
qux = bar
```

I see this incorrect error:
```
$ stack exec liquid -- t.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Cleaned Files ******************************************************
 

**** DONE:  Parsed All Specifications ******************************************
 

**** DONE:  Loaded Targets *****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  generateConstraints ************************************************
 
Working   0% [.................................................................]
Done solving.

**** DONE:  solve **************************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: UNSAFE ************************************************************


 t.hs:28:7-9: Error: Liquid Type Mismatch
 
 28 | qux = bar
            ^^^
 
   Inferred type
     VV : {VV : (GHC.Types.Int <>) | VV == 4}
  
   not a subtype of Required type
     VV : {VV : (GHC.Types.Int <>) | VV == sizeOf (Data.Proxy.Proxy : (Data.Proxy.Proxy  GHC.Word.Word32))}
  
   In Context
$
```

**Comment by ranjitjhala** [comment]
Could this have to do with the recently fixed Word literal issue..?

**Comment by gridaphobe** [comment]
I think the problem is not so much that the instance measure is unused, but that we don't support type ascriptions in refinements, ie we don't support the

```
Proxy :: Proxy Word32
```

expression. I'm honestly surprised that it even parses.

**Comment by j6carey** [comment]
Here is a variant that does not use `Proxy :: Proxy Word32`:
```haskell
module T where

import Data.Proxy
import Data.Word
import GHC.Ptr

{-@ class measure sizeOf :: forall a . Data.Proxy.Proxy a -> Int @-}
{-@
instance measure sizeOf :: (Data.Proxy.Proxy Data.Word.Word16) -> Int
sizeOf (Proxy) = 2
@-}
{-@
instance measure sizeOf :: (Data.Proxy.Proxy Data.Word.Word32) -> Int
sizeOf (Proxy) = 4
@-}

{-@
measure ptrToProxy :: forall a . Ptr a -> (Proxy a)
ptrToProxy (Ptr a) = Proxy
@-}

{-@
bar :: { p : Ptr Word32 | plen p >= (sizeOf (ptrToProxy p)) }
    -> ()
@-}
bar :: Ptr Word32 -> ()
bar _ = ()

{-@
qux :: { p : Ptr Word32 | plen p >= 4 }
    -> ()
@-}
qux :: Ptr Word32 -> ()
qux = bar
```

The output:
```
...
**** RESULT: UNSAFE ************************************************************


 t.hs:34:7-9: Error: Liquid Type Mismatch
 
 34 | qux = bar
            ^^^
 
   Inferred type
     VV : {VV : (GHC.Ptr.Ptr <> (GHC.Word.Word32 <>)) | plen VV >= 4}
  
   not a subtype of Required type
     VV : {VV : (GHC.Ptr.Ptr <> (GHC.Word.Word32 <>)) | plen VV >= sizeOf (ptrToProxy VV)}
  
   In Context
```

**Comment by j6carey** [comment]
I reproduced the issue with what seem to be the latest commits:
```
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 22d2ea080b600a5999bfb8a053c7ee1613d0caf4
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 37955d5493ccc3bb55fbb264a9b6fb5e7f7d9c7e
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/prover.git
    commit: b248a719bd7b2a7fa635c7b2d78bd28a2ccbf2b1
  extra-dep: true
```
