### ISSUE TITLE
travis does not install z3 lib

### ISSUE THREAD

**Issue by alanz** [ucsd-progsys/liquidhaskell#960]
Travis runs ubuntu precise (12.04).

Z3 is not available via apt.

It seems there are 2 options

1. Install z3 from source
2. Run via a docker image, with a later distribution

Are there any preferences?

**Comment by alanz** [comment]
I guess CVC4 or MathSat are also options.

**Comment by alanz** [comment]
This seems to work

```yaml
addons:
  apt:
    packages:
      - libz3-dev
    sources:
      - sourceline: ppa:hvr/z3
```
